name: deploy-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Django Coverage action
      uses: actions/python-django-coverage-gitHub-action@0.9
      with:
        django-app: 'sample_app'
        minimum-coverage: '86'

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/repo-python:latest
        tagging: true
