name: deploy-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Dependencies Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Test
      uses: onichandame/python-test-action@master
      with:
        deps_list: 'requirement'

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/repo-python:latest
        tagging: true
